project:
  type: book
  output-dir: docs
book:
  title: HSMA - Machine Learning Notebooks
  author: Dan Chalk & Sammi Rosser
  date: 31/07/2024
  chapters:
  - index.qmd
  - part: 4B - Logistic Regression
    chapters:
    - 4b_log_reg_tutorial_1.ipynb
    - 4b_log_reg_tutorial_2.ipynb
    - 4b_ex_1_solution.ipynb
  - part: 4D/4E - Tree-based models for classification
    chapters:
    - 4d_decision_tree_titanic.ipynb
    - 4d_decision_tree_stroke_exercise_SOLUTION.ipynb
    - 4d_random_forest_titanic.ipynb
    - 4d_random_forest_stroke_exercise_SOLUTION.ipynb
    - 4e_boosting_titanic.ipynb
  - part: 4E - Tree-based models for regression
    chapters:
    - 4e_tree_based_models_regression.ipynb
    - 4e_regression_tree_exercise_SOLUTION.ipynb
  - part: 4F - Neural Networks
    chapters:
    - 4f_HSMA_neural_nets.ipynb
    - 4f_ex_1_solution.ipynb
  - part: 4G - Explainable AI
    chapters:
    - 4g_logistic_regression_titanic_feature_importance_prediction_uncertainty.ipynb
    - 4g_pdp_ice_feature_importance_shap_table_tree_classification_titanic.ipynb
    - 4g_shap_plots_tree_classification_example_titanic.ipynb
    - 4g_shap_plots_tree_regression_example_diabetes.ipynb
    - 4g_shap_neural_nets.ipynb
    - 4g_1_xai_classification_exercise_SOLUTION.ipynb
    - 4g_2a_classification_boosting_exercise_SOLUTION.ipynb
    - 4g_2b_regression_tree_exercise_shap_SOLUTION.ipynb
  - part: 4I - Synthetic Data
    chapters:
    - 4i_synthetic_data_SMOTE.ipynb
    - 4i_Exercise_1_Solution.ipynb
  - part: 4J - Model Optimisation
    chapters:
    - 4j_auto_ml.ipynb
    - 4j_data_preprocessing_and_eda.ipynb
    - 4j_ensembles_voting.ipynb
    - 4j_feature_engineering.ipynb
    - 4j_feature_selection.ipynb
    - 4j_hyperparameter_optimisation.ipynb
    - 4j_imbalanced_data.ipynb
    - 4j_k_fold_validation.ipynb
    - 4j_missing_data_imputation.ipynb
    - 4j_model_calibration.ipynb
    - 4j_pipelines.ipynb
  cover-image: resources/cover_image_robot.jpeg
  favicon: resources/logos/hsma_logo_transparent_background_large.png
  search: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: false
    background: '#8A1E1E'
    right:
    - icon: github
      href: https://github.com/hsma-programme/
      aria-label: GitHub
  sidebar:
    search: true
    style: docked
    logo: resources/logos/hsma_logo_transparent_background_large.png
    background: '#111111'
bibliography: references.bib
format:
  html:
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      dark:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - theme-light.scss
      - resources/fonts/css/lexend.css
    grid:
      sidebar-width: 250px
